In [ ]:
pip install ucimlrepo

In [ ]:
# 1) Load data into a 2-D array called iris.

from ucimlrepo import fetch_ucirepo
import numpy as np
import pandas as pd
# fetch dataset
iris = fetch_ucirepo(id=53)

# data (as pandas dataframes)
X = iris.data.features
X_bkp = iris.data.features
y = iris.data.targets
y_bkp = iris.data.targets

# 2) Drop column at index 4

X = X.drop(["sepal length"], axis = 1)
print(X)

X_np = np.array(X)
y_np = np.array(y)

     sepal width  petal length  petal width
0            3.5           1.4          0.2
1            3.0           1.4          0.2
2            3.2           1.3          0.2
3            3.1           1.5          0.2
4            3.6           1.4          0.2
..           ...           ...          ...
145          3.0           5.2          2.3
146          2.5           5.0          1.9
147          3.0           5.2          2.0
148          3.4           5.4          2.3
149          3.0           5.1          1.8

[150 rows x 3 columns]


In [ ]:
# 3) Display shape, dimensions, and size of iris

print("Shape:", X_np.shape)
print("Dimensions:", X_np.ndim)
print("Size:", X_np.size)

Shape: (150, 3)
Dimensions: 2
Size: 450


In [ ]:
# 4) Split iris into three 2-D arrays for different species

# X.describe()
# y.describe()
# X.drop(index='3')
# iris1 = X.iloc[:50]
# iris2 = X.iloc[50:100]
# iris3 = X.iloc[100:150]
splitArr = np.array_split(X_np, 3)

iris1, iris2, iris3 = splitArr

In [ ]:
# 5) Print iris1, iris2, iris3

print("Iris1:\n", iris1)
print("Iris2:\n", iris2)
print("Iris3:\n", iris3)

Iris1:
 [[3.5 1.4 0.2]
 [3.  1.4 0.2]
 [3.2 1.3 0.2]
 [3.1 1.5 0.2]
 [3.6 1.4 0.2]
 [3.9 1.7 0.4]
 [3.4 1.4 0.3]
 [3.4 1.5 0.2]
 [2.9 1.4 0.2]
 [3.1 1.5 0.1]
 [3.7 1.5 0.2]
 [3.4 1.6 0.2]
 [3.  1.4 0.1]
 [3.  1.1 0.1]
 [4.  1.2 0.2]
 [4.4 1.5 0.4]
 [3.9 1.3 0.4]
 [3.5 1.4 0.3]
 [3.8 1.7 0.3]
 [3.8 1.5 0.3]
 [3.4 1.7 0.2]
 [3.7 1.5 0.4]
 [3.6 1.  0.2]
 [3.3 1.7 0.5]
 [3.4 1.9 0.2]
 [3.  1.6 0.2]
 [3.4 1.6 0.4]
 [3.5 1.5 0.2]
 [3.4 1.4 0.2]
 [3.2 1.6 0.2]
 [3.1 1.6 0.2]
 [3.4 1.5 0.4]
 [4.1 1.5 0.1]
 [4.2 1.4 0.2]
 [3.1 1.5 0.1]
 [3.2 1.2 0.2]
 [3.5 1.3 0.2]
 [3.1 1.5 0.1]
 [3.  1.3 0.2]
 [3.4 1.5 0.2]
 [3.5 1.3 0.3]
 [2.3 1.3 0.3]
 [3.2 1.3 0.2]
 [3.5 1.6 0.6]
 [3.8 1.9 0.4]
 [3.  1.4 0.3]
 [3.8 1.6 0.2]
 [3.2 1.4 0.2]
 [3.7 1.5 0.2]
 [3.3 1.4 0.2]]
Iris2:
 [[3.2 4.7 1.4]
 [3.2 4.5 1.5]
 [3.1 4.9 1.5]
 [2.3 4.  1.3]
 [2.8 4.6 1.5]
 [2.8 4.5 1.3]
 [3.3 4.7 1.6]
 [2.4 3.3 1. ]
 [2.9 4.6 1.3]
 [2.7 3.9 1.4]
 [2.  3.5 1. ]
 [3.  4.2 1.5]
 [2.2 4.  1. ]
 [2.9 4.7 1.4]
 [2.9 3.6 1.3]
 [3.1 4.

In [ ]:
# 6) Create a 1-D array header

headerArr = ["sepal length", "sepal width", "petal length", "petal width"]

header = np.array(headerArr)

# 7) Display the array header

print(header)

['sepal length' 'sepal width' 'petal length' 'petal width']


In [ ]:
# 8) Find max, min, mean, and standard deviation for columns of iris

iris_min = np.round(np.min(X_np, axis=0), 2)
#print(iris_min)
iris_max = np.round(np.max(X_np, axis=0), 2)
#print(iris_max)
iris_avg = np.round(np.mean(X_np, axis=0), 2)
print(iris_avg)
iris_std = np.round(np.std(X_np, axis=0), 2)
#print(iris_std)
iris_var = np.round(np.var(X_np, axis=0), 2)
#print(iris_var)

[3.05 3.76 1.2 ]


In [ ]:
# 9) Find max, min, mean, and std for columns of iris1, iris2, iris3

iris1_min = iris1.min(axis = 0)
#print(iris1_min)
iris1_max = iris1.max(axis = 0)
#print(iris1_max)
iris1_avg = iris1.mean(axis = 0)
print(iris1_avg)
iris1_std = iris1.std(axis = 0)
#print(iris1_std)
iris1_var = iris1.var(axis = 0)
#print(iris1_var)

iris2_min = iris2.min(axis = 0)
#print(iris2_min)
iris2_max = iris2.max(axis = 0)
#print(iris2_max)
iris2_avg = iris2.mean(axis = 0)
print(iris2_avg)
iris2_std = iris2.std(axis = 0)
#print(iris2_std)
iris2_var = iris2.var(axis = 0)
#print(iris2_var)

iris3_min = iris3.min(axis = 0)
#print(iris3_min)
iris3_max = iris3.max(axis = 0)
#print(iris3_max)
iris3_avg = iris3.mean(axis = 0)
print(iris3_avg)
iris3_std = iris3.std(axis = 0)
#print(iris3_std)
iris3_var = iris3.var(axis = 0)
#print(iris3_var)


[3.418 1.464 0.244]
[2.77  4.26  1.326]
[2.974 5.552 2.026]


In [ ]:
# 11) Compare Iris setosa's average sepal width to that of Iris virginica

setosa_sepal_width_avg = np.mean(iris1[:, 0])
virginica_sepal_width_avg = np.mean(iris3[:, 0])

print(f"Average Setosa sepal width: {setosa_sepal_width_avg}")
print(f"Average Verginica sepal width: {virginica_sepal_width_avg}")
print(f"Difference: {abs(setosa_sepal_width_avg - virginica_sepal_width_avg):.4f}")

Average Setosa sepal width: 3.418
Average Verginica sepal width: 2.974
Difference: 0.4440


In [ ]:
# 12) Compare Iris setosa's average petal length to that of Iris virginica

setosa_petal_length_avg = np.mean(iris1[:, 1])
virginica_petal_length_avg = np.mean(iris3[:, 1])

print(f"Average Setosa petal length: {setosa_petal_length_avg}")
print(f"Average Verginica petal length: {virginica_petal_length_avg}")
print(f"Difference: {abs(setosa_petal_length_avg - virginica_petal_length_avg):.4f}")

Average Setosa petal length: 1.464
Average Verginica petal length: 5.5520000000000005
Difference: 4.0880


In [ ]:
# 13) Compare Iris setosa's average petal width to that of Iris virginica

setosa_petal_width_avg = np.mean(iris1[:, 2])
virginica_petal_width_avg = np.mean(iris3[:, 2])

print(f"Average Setosa petal width: {setosa_petal_width_avg}")
print(f"Average Verginica petal width: {virginica_petal_width_avg}")
print(f"Difference: {abs(setosa_petal_width_avg - virginica_petal_width_avg):.4f}")

Average Setosa petal width: 0.244
Average Verginica petal width: 2.0260000000000002
Difference: 1.7820


In [ ]:
# iris1 = iris1.reset_index(drop = True)
# iris2 = iris2.reset_index(drop = True)
# iris3 = iris3.reset_index(drop = True)

In [ ]:
# 14) Save iris_avg to a CSV file

# Specify the file path where you want to save the CSV file
file_path = 'IrisMeanValues.csv'

# Use savetxt to export the array to a CSV file
np.savetxt(file_path, iris_avg, delimiter=',', comments='')

iris_avg_df = pd.DataFrame({'sepal width': [3.054], 'petal length': [3.75866667], 'petal width': [1.19866667]})

# Specify the file path where you want to save the CSV file
file_path = 'IrisMeanValues_pd.csv'

# Use to_csv to export the DataFrame to a CSV file
iris_avg_df.to_csv(file_path, index=False)


In [ ]:
# 15) Save iris_max, iris_avg, iris_min to a CSV file

iris_stats_combined = np.vstack((iris_max, iris_avg, iris_min))
np.savetxt('IrisStat.txt', iris_stats_combined, delimiter=',', header=','.join(header[:-1]), comments='')